include:
  - project: 'repos/releng/docpub'
    file: 'includes/publish.yml'

stages:
  - docs

build-documentation:
  stage: docs
  image: python:3.13

  before_script:
    - pip install uv
    - uv sync

  script:
    - uv run sphinx-build -b html docs/source generated-documentation

  variables:
    DOCS_DIR: generated-documentation

  extends:
    - .docpub:build-docs

publish-documentation:
  stage: docs

  needs:
    - build-documentation

  variables:
    PUB_LOCATION: plantilla-chatbot

  extends:
    - .docpub:publish-docs
